### PR TITLE
Keystone token issues

### PR DESCRIPTION
**Pull request by JohnGarbutt**

### CODE REVIEW

**Comment by JohnGarbutt** [comment]
This seems to have fixed the issue, although there are other ways we could fix it.

**Review by dougszumski — COMMENTED** [review]
I suppose an alternative would be to add this as Kayobe config to minimise the number of patches that we carry on this Kolla-Ansible fork.

**Comment by JohnGarbutt** [comment]
This is a backport of the upstream patch. The problem of adding this in kayobe is we stop being idempotent again, we start fighting what kolla-ansible is writing out.

We probably need to rebase with upstream stein soon, and drop a bunch of these if we can, or at least make sure they are all tracking upstream patches, so they can be dropped as they merge upstream.

**Review by dougszumski — APPROVED** [review]
Hmm, not sure I follow, won't the Kayobe config just be provided as Kolla Ansible custom config and get merged with the defaults here: `https://github.com/stackhpc/kolla-ansible/blob/master/ansible/roles/keystone/tasks/config.yml#L56` ?

Anyway, not to worry, I know you submitted it upstream, thanks for fixing.

**Comment by JohnGarbutt** [comment]
Oh... I see what you mean now. Just override in kayobe. That probably is easier.

**Pull request merged**
